config/routes.rb
Rentstore::Application.routes.draw do
  

resources :messages do
   collection do
      post :delete_selected
   end
end

resources :stores do
  resources :items
end

resources :stores

  match "rents/:id" => "rents#show", :via => [:get]
  match "rents" => "rents#index", :via => [:get]

   root :to => "rents#index"

  match "survey"        => "servey#show"
resources :interests
  match "a_item/:id" => "a_rents#show", :via => [:get]
  match "a_item"     => "a_rents#index", :via => [:get]
  match "a"          => "a_rents#index"
  

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible  :subject, :body, :recipient_id
  is_private_message
  
end

app/controllers/messages_controller.rb
class MessagesController < Spree::BaseController
  
  before_filter :set_user
  
  def index
    if params[:mailbox] == "sent"
      @messages = @user.sent_messages
    else
      @messages = @user.received_messages
    end
    respond_to do |format|
       format.html # index.html.erb
       format.json { render json: @messages }
     end
    
  end
  
  def show
    @message = Message.read(params[:id], current_user)
    respond_to do |format|
       format.html # show.html.erb
       format.json { render json: @message }
     end
    
  end
  
  def new
    @message = Message.new

    if params[:reply_to]
      @reply_to = @user.received_messages.find(params[:reply_to])
      unless @reply_to.nil?
        @message.to = @reply_to.sender.login
        @message.subject = "Re: #{@reply_to.subject}"
        @message.body = "\n\n*Original message*\n\n #{@reply_to.body}"
      end
    end
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
    
  end
  
  def create
    @message = Message.new(params[:message])
    @message.sender = @user
    @message.recipient = @user # User.find_by_login(params[:message][:to])

    if @message.save
      flash[:notice] = "Message sent"
      redirect_to messages_path
    else
      render :action => :new
    end
  end
  
  def delete_selected
    if request.post?
      if params[:delete]
        params[:delete].each { |id|
          @message = Message.find(:first, :conditions => ["messages.id = ? AND (sender_id = ? OR recipient_id = ?)", id, @user, @user])
          @message.mark_deleted(@user) unless @message.nil?
        }
        flash[:notice] = "Messages deleted"
      end
      redirect_to messages_path
    end
  end
  
  private
    def set_user
      @user =  Thread.current[:user]
    end
end

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/_inbox.html.erb
<h2>Inbox</h2>
<table>
	<tr>
		<th>Del?</th>
		<th>Sent</th>
		<th>Sender</th>
		<th>Sent</th>
	</tr>
	<% if @messages.size == 0 %>
		<tr>
			<td colspan="4">
				No messages
			</td>
		</tr>
	<% else %>
		<% for message in @messages %>
			<tr>
				<td><%= check_box_tag "delete[]", message.id %></td>
				<td>
					<% if message.read? %>
					  <%= link_to h(message.subject), message_path(message) %>
					<% else %>
					  <%= link_to "#{h(message.subject)} (unread)", message_path(message) %>
					<% end %>
				</td>
				<td><%= link_to h(message.sender.id), user_path(@user) %></td>
		    <td><%=h message.created_at.to_s(:long) %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="4">
				<%= submit_tag "Delete" %>
			</td>
		</tr>
	<% end %>
</table>
<%= link_to "Sent", messages_path(:mailbox => :sent)%> |
<%= link_to "Compose", new_message_path %>

app/views/messages/_sent.html.erb
<h2>Sent</h2>
<table>
	<tr>
		<th>Del?</th>
		<th>Subject</th>
		<th>To</th>
		<th>Sent</th>
	</tr>
	<% if @messages.size == 0 %>
		<tr>
			<td colspan="4">
				No messages
			</td>
		</tr>
	<% else %>
		<% for message in @messages %>
			<tr>
				<td><%= check_box_tag "delete[]", message.id %></td>
				<td><%= link_to h(message.subject), message_path(message) %></td>
  			<td><%= link_to h(message.recipient.id), user_path(@user) %></td>
			  <td><%=h message.created_at.to_s(:long) %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="4">
				<%= submit_tag "Delete" %>
			</td>
		</tr>
 	<% end %>
</table>
<%= link_to "Inbox", messages_path  %>

app/views/messages/index.html.erb
<div><h2>Message</h2>
	<%= form_tag delete_selected_messages_path, :method => :post  do %>

	<% if params[:mailbox] == "sent" %>
			<%= render :partial => "sent" %>
	<% else %>
			<%= render :partial => "inbox" %>
	<% end %>
	
	<% end %>
</form>
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p><strong>From:</strong> <%= @message.sender == @user ? link_to("You", user_path(@user)) : link_to(h(@message.sender.login), user_path(@user)) %></p>
<p><strong>Received:</strong> <%= @message.created_at.to_s(:long) %></p>
<p><strong>To:</strong> <%= @message.recipient == @user ? link_to("You", user_path(@user)) : link_to(h(@message.recipient.login), user_path(@user)) %></p>
<p>
  <strong>Message</strong><br />
  <%=h @message.body %>
</p>
<p>
  <% if @message.recipient == @user %>
	  <%= link_to "Reply", new_message_path(:reply_to => @message) %> |
  <% end %>
  <%= link_to "Inbox", messages_path %>
</p>