config/routes.rb
Rentstore::Application.routes.draw do
  

resources :messages do
   collection do
      post :delete_selected
   end
end

resources :stores do
  resources :items
end

resources :stores

  match "rents/:id" => "rents#show", :via => [:get]
  match "rents" => "rents#index", :via => [:get]

   root :to => "rents#index"

  match "survey"        => "servey#show"
resources :interests
  match "a_item/:id" => "a_rents#show", :via => [:get]
  match "a_item"     => "a_rents#index", :via => [:get]
  match "a"          => "a_rents#index"
  

end

app/controllers/users_controller.rb
class UsersController < Spree::BaseController
  prepend_before_filter :load_object, :only => [:show, :edit, :update]
  prepend_before_filter :authorize_actions, :only => :new

  def show
    @orders = @user.orders.complete
    @stores = @user.stores
    @items  = Array.new
    @stores.each do |s| 
        @items += s.items
    end
    
  end

  def create
    @user = User.new(params[:user])
    if @user.save

      if current_order
        current_order.associate_user!(@user)
        session[:guest_token] = nil
      end

      redirect_back_or_default(root_url)
    else
      render 'new'
    end

  end

  def update
    if @user.update_attributes(params[:user])
      if params[:user][:password].present?
        # this logic needed b/c devise wants to log us out after password changes
        user = User.reset_password_by_token(params[:user])
        sign_in(@user, :event => :authentication, :bypass => !Spree::Auth::Config[:signout_after_password_change])
      end
      flash.notice = I18n.t("account_updated")
      redirect_to account_url
    else
      render 'edit'
    end

  end

  private
    def load_object
      @user ||= current_user
      authorize! params[:action].to_sym, @user
    end

    def authorize_actions
      authorize! params[:action].to_sym, User
    end

    def accurate_title
      I18n.t(:account)
    end

end

app/views/users/edit.html.erb
<%= render 'shared/error_messages', :target => @user %>

<h1><%= t(:editing_user) %></h1>

<%= form_for @user, :html => { :method => :put } do |f| %>
  <%= render 'shared/user_form', :f => f %>
  <p>
    <%= f.submit t(:update) %>
  </p>
<% end %>

app/views/users/show.android.erb
<h1><%= t(:my_account) %></h1>

<div data-hook="account_summary">
  <dl id="user-info">
    <dt><%= t(:email) %></dt>
    <dd><%= @user.email %></dd>
  </dl>
  <p><%= link_to t(:edit), edit_account_path %></p>
</div>

<div data-hook="account_my_items">
  <h2><%= "My Rental Items" %> </h2>
  <% if @items.present? %>
     <table class="item-summary" style="width:545px;">
			<tr><td><b>Store Name :</b> <%= @stores.first.name %><td><%= link_to 'Edit', edit_store_path(@stores.first) %></td></tr>
			  <tr>
			    <th>Item<br/>Description</th>
			    <th>Location</th>
			    <th></th>
			  </tr>

			<% @items.each do |item| %>
			  <tr>
			    <td><%= item.description %></td>
			    <td><%= item.location %></td>
			    <td><%= link_to 'Edit', edit_store_item_path(item.store,item) %></td>
			  </tr>
			<% end %>
		<tr><td><%= link_to 'Add Item', new_store_item_path(@stores.first) %></td></tr>
     </table>


  <% else %>
    <% if @stores.present? %>
       <%= link_to 'Add Item', new_store_item_path(@stores.first) %>
    <% else %>
       <%= link_to "No Items for rents, sign up now!!!",  new_store_path %>
   <% end %>
  <% end %>
  <br />

</div>

<div data-hook="account_my_orders">
  <h2><%= t(:my_orders) %></h2>
  <% if @orders.present? %>
    <table class="order-summary" style="width:545px;">
      <thead>
        <tr>
          <th><%= t(:order_number) %></th>
          <th><%= t(:order_date) %></th>
          <th><%= t(:status) %></th>
          <th><%= t(:payment_state) %></th>
          <th><%= t(:shipment_state) %></th>
          <th><%= t(:total) %></th>
        </tr>
      </thead>
      <tbody>
      <% @orders.each do |order| %>
        <tr class="<%= cycle('even', 'odd') %>">
          <td><%= link_to order.number, order_url(order) %></td>
          <td><%= l order.created_at.to_date %></td>
          <td><%= t(order.state).titleize %></td>
          <td><%= t("payment_states.#{order.payment_state}") if order.payment_state %></td>
          <td><%= t("shipment_states.#{order.shipment_state}") if order.shipment_state %></td>
          <td><%= number_to_currency order.total %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <p><%= t(:you_have_no_orders_yet) %></p>
  <% end %>
  <br />

</div>

app/views/users/show.html.erb
<h1><%= t(:my_account) %></h1>

<div data-hook="account_summary">
  <dl id="user-info">
    <dt><%= t(:email) %></dt>
    <dd><%= @user.email %></dd>
  </dl>
  <p><%= link_to t(:edit), edit_account_path %></p>
</div>

<div data-hook="account_my_items">
  <h2><%= "My Rental Items" %> </h2>
  <% if @items.present? %>
     <table class="item-summary" style="width:545px;">
			<tr><td><b>Store Name :</b> <%= @stores.first.name %><td><%= link_to 'Edit', edit_store_path(@stores.first) %></td></tr>
			  <tr>
			    <th>Item<br/>Description</th>
			    <th>Location</th>
			    <th></th>
			  </tr>

			<% @items.each do |item| %>
			  <tr>
			    <td><%= item.description %></td>
			    <td><%= item.location %></td>
			    <td><%= link_to 'Edit', edit_store_item_path(item.store,item) %></td>
			  </tr>
			<% end %>
		<tr><td><%= link_to 'Add Item', new_store_item_path(@stores.first) %></td></tr>
     </table>


  <% else %>
    <% if @stores.present? %>
       <%= link_to 'Add Item', new_store_item_path(@stores.first) %>
    <% else %>
       <%= link_to "No Items for rents, sign up now!!!",  new_store_path %>
   <% end %>
  <% end %>
  <br />

</div>

<div data-hook="account_my_orders">
  <h2><%= t(:my_orders) %></h2>
  <% if @orders.present? %>
    <table class="order-summary" style="width:545px;">
      <thead>
        <tr>
          <th><%= t(:order_number) %></th>
          <th><%= t(:order_date) %></th>
          <th><%= t(:status) %></th>
          <th><%= t(:payment_state) %></th>
          <th><%= t(:shipment_state) %></th>
          <th><%= t(:total) %></th>
        </tr>
      </thead>
      <tbody>
      <% @orders.each do |order| %>
        <tr class="<%= cycle('even', 'odd') %>">
          <td><%= link_to order.number, order_url(order) %></td>
          <td><%= l order.created_at.to_date %></td>
          <td><%= t(order.state).titleize %></td>
          <td><%= t("payment_states.#{order.payment_state}") if order.payment_state %></td>
          <td><%= t("shipment_states.#{order.shipment_state}") if order.shipment_state %></td>
          <td><%= number_to_currency order.total %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <p><%= t(:you_have_no_orders_yet) %></p>
  <% end %>
  <br />

</div>