config/routes.rb
Rentstore::Application.routes.draw do
  

resources :messages do
   collection do
      post :delete_selected
   end
end

resources :stores do
  resources :items
end

resources :stores

  match "rents/:id" => "rents#show", :via => [:get]
  match "rents" => "rents#index", :via => [:get]

   root :to => "rents#index"

  match "survey"        => "servey#show"
resources :interests
  match "a_item/:id" => "a_rents#show", :via => [:get]
  match "a_item"     => "a_rents#index", :via => [:get]
  match "a"          => "a_rents#index"
  

end

app/views/shared/_error_messages.android.erb
<% if target && target.errors.any? %>
  <div id="errorExplanation" class="errorExplanation" data-hook>
    <h2><%= t(:errors_prohibited_this_record_from_being_saved, :count => target.errors.count) %>:</h2>
    <p><%= t(:there_were_problems_with_the_following_fields) %>:</p>
     <ul>
     <% target.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if flash.any? %>
  <div id="flash">
    <% flash.each do |key, value| %>
      <p>
        <%= value %>
      </p>
    <% end %>
  </div>
<% end%>

app/views/shared/_login.android.erb
<%= form_for :user, :url => user_session_path do |f| %>
  <div id="password-credentials">
    <p>
      <%= f.label :email, t(:email) %><br />
      <%= f.text_field :email, :class => 'title' %>
    </p>
    <p>
      <%= f.label :password, t(:password) %><br />
      <%= f.password_field :password, :class => 'title' %>
    </p>
  </div>
  <p>
    <label>
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me, t(:remember_me) %>
    </label>
  </p>

  <p><%= f.submit t(:log_in), :class => 'button primary'%></p>
<% end %>

app/views/shared/_login.html.erb
<%= form_for :user, :url => user_session_path do |f| %>
  <div id="password-credentials">
    <p>
      <%= f.label :email, t(:email) %><br />
      <%= f.text_field :email, :class => 'title' %>
    </p>
    <p>
      <%= f.label :password, t(:password) %><br />
      <%= f.password_field :password, :class => 'title' %>
    </p>
  </div>
  <p>
    <label>
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me, t(:remember_me) %>
    </label>
  </p>

  <p><%= f.submit t(:log_in), :class => 'button primary'%></p>
<% end %>

app/views/shared/_login_bar.html.erb
<% if current_user %>
  <li><%= link_to t(:my_account), account_path %></li>
  <li><%= link_to t(:logout), destroy_user_session_path %></li>
<% else %>
  <li><%= link_to t(:log_in), login_path %></li>
<% end %>

app/views/shared/_nav_bar.html.erb
<li id="search-bar" data-hook>
  <%= render 'shared/search' %>
</li>

<li>
<% if @user.present? && @user.stores.present? %>
<%= form_tag store_items_path(@user.stores.first), :method => "get" %>
<button  type="submit" value="submit" style="float:left;"  >
My Rentals
</button>
</form>
<% else %>

<% end %>
</li>
<% if store_menu? %>
  <%= render 'shared/store_menu' %>
<% end %>

app/views/shared/_socials.android.erb
<% if !current_user || !current_user.user_authentications %>
  <h2><%= t(:sign_in_through_one_of_these_services) %>:</h2>
<% end %>
<% AuthenticationMethod.where(:environment => ::Rails.env).each do |user| %>
  <%- img = Rails.application.assets.find_asset("store/social/#{user.preferred_provider}_32.png").present? ? "store/social/#{user.preferred_provider}_32.png" : "store/social/spree_32.png" -%>
  <%= link_to(image_tag(img, :size => "32x32", :alt => "#{user.preferred_provider}"), user_authentication_omniauth_authorize_path(user.preferred_provider.to_sym), :title => "#{t(:sign_in_with)} #{user.preferred_provider}") if user.active %>
<% end %>

app/views/shared/_user_form.android.erb
<p>
  <%= f.label :email, t(:email) %><br />
  <%= f.text_field :email, :class => 'title' %>
</p>
<div id="password-credentials">
  <p>
    <%= f.label :password, t(:password) %><br />
    <%= f.password_field :password, :class => 'title' %>
  </p>

  <p>
    <%= f.label :password_confirmation, t(:confirm_password) %><br />
    <%= f.password_field :password_confirmation, :class => 'title' %>
  </p>
</div>

<div data-hook="signup_below_password_fields"></div>

app/views/shared/_user_form.html.erb
<p>
  <%= f.label :email, t(:email) %><br />
  <%= f.text_field :email, :class => 'title' %>
</p>
<div id="password-credentials">
  <p>
    <%= f.label :password, t(:password) %><br />
    <%= f.password_field :password, :class => 'title' %>
  </p>

  <p>
    <%= f.label :password_confirmation, t(:confirm_password) %><br />
    <%= f.password_field :password_confirmation, :class => 'title' %>
  </p>
</div>

<div data-hook="signup_below_password_fields"></div>