config/routes.rb
Rentstore::Application.routes.draw do
  

resources :messages do
   collection do
      post :delete_selected
   end
end

resources :stores do
  resources :items
end

resources :stores

  match "rents/:id" => "rents#show", :via => [:get]
  match "rents" => "rents#index", :via => [:get]

   root :to => "rents#index"

  match "survey"        => "servey#show"
resources :interests
  match "a_item/:id" => "a_rents#show", :via => [:get]
  match "a_item"     => "a_rents#index", :via => [:get]
  match "a"          => "a_rents#index"
  

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :title, :description, :location, :active
  belongs_to :store
  
  validates :title,  :presence => true,
                     :length   => { :maximum => 150 }
  validates :description, :presence => true
  validates :location, :presence => true
  
  def deactivate 
     self.active = false
   end
   
   def activate 
     self.active = true
   end
        
   def active?
     self.active
   end
  
end

app/controllers/items_controller.rb
class ItemsController < Spree::BaseController
  
  #controller for maintaining items
  
  before_filter :set_store
  # GET /items
  # GET /items.json
  def index

    if @store.nil? || @store.user_id != User.current.id 
      redirect_to root_path
    else
      @items = @store.items
      respond_to do |format|
        format.android
        format.html # index.html.erb
        format.json { render json: @items }
      end
    end
    
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find_by_id_and_store_id(params[:id],params[:store_id])
    if @item.nil? || @item.store.user_id != User.current.id 
      redirect_to root_path
    else
      respond_to do |format|
        format.android # show.html.erb
        format.html # show.html.erb
        format.json { render json: @item }
      end
    end
    
  end

  # GET /items/new
  # GET /items/new.json
  def new
    
    if @store.nil? || @store.user_id != User.current.id 
      redirect_to root_path
    else
    
    @item = Item.new
    @item.location = "Portland, OR"
    @item.active   = true
    
    respond_to do |format|
      format.android # new.html.erb
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end
end
  # GET /items/1/edit
  def edit
    if @store.nil? || @store.user_id != User.current.id 
      redirect_to root_path
    else
    
    @item = Item.find(params[:id])
  end
end

  # POST /items
  # POST /items.json
  def create
    if @store.nil? || @store.user_id != User.current.id 
      redirect_to root_path
    else
    
    @item = Item.new(params[:item])
    @item.active   = true
    
    @item.store = @store
    respond_to do |format|
      if @item.save
        format.android { redirect_to store_items_path(@store), notice: 'Item was successfully created.' }
        format.html    { redirect_to store_items_path(@store), notice: 'Item was successfully created.' }
        format.json    { render json: @item, status: :created, location: @item }
      else
        format.html {  render action: "new" }
        format.android {  render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
    end
    
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    if @store.nil? || @store.user_id != User.current.id 
      redirect_to root_path
    else
    
    @item = Item.find(params[:id])
 
    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.android { redirect_to store_items_path(@store), notice: 'Item was successfully updated.' }
        format.html { redirect_to store_items_path(@store), notice: 'Item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.android { render action: "edit"}
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    if @store.nil? || @store.user_id != User.current.id 
      redirect_to root_path
    else
    
      @item = Item.find(params[:id])
      @item.destroy

      respond_to do |format|
        format.android { redirect_to store_items_path(@store) }
        format.html    { redirect_to store_items_path(@store) }
        format.json    { head :ok }
      end
    end
  end
  
  private
    def set_store
      if  !User.current.nil? 
        @store = Store.find_by_id_and_user_id(params[:store_id], User.current.id)
      end
    end

  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

app/views/items/edit.android.erb
<h1>Editing item</h1>

<%= form_for @item, :url => store_item_path(@store,@item) do |f| %>
<% if @item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :description %><br />
  <%= f.text_field :description %>
</div>
<div class="field">
  <%= f.label :location %><br />
  <%= f.text_field :location %>
</div>
<div class="actions">
  <%= f.submit %>
</div>

<% end %>

<%= link_to 'Destroy', store_item_path(params[:store_id],@item), confirm: 'Are you sure?', method: :delete %></td>
<%= link_to 'Show', store_item_path(params[:store_id],@item) %> |
<%= link_to 'Items', store_items_path(params[:store_id]) %>

app/views/items/edit.html.erb
<h1>Edit rental</h1>

<%= form_for @item, :url => store_item_path(@store,@item) do |f| %>
<% if @item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="field">
 <%= f.label :active %>
  <%= f.check_box :active %>
</div>
<div class="field">
  <%= f.label :location %><br />
  <%= f.text_field :location %>
</div>
<div class="field">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :description %><br />
  <%= f.text_area :description, :cols => 132, :rows => 20  %>
</div>

<div class="invited">
  <table>
  <tr>
  <th>Item's invitation list</th><th></th><th></th><th>View Location</th><th>View Title</th><th>View Description</th>
  </tr>
  <tr>
  <td>Everyone</td>  
  </tr>
  <tr>
  <td>All Renters</td>  
  </tr>
  <tr>
  <td>Renters</td><td>RS User Info</td>  
  </tr>
  <tr>
  <td>All Facebook friends</td><td>FB Info</td>
  </tr>
  <tr>
  <td>Facebook friend</td><td>FB Info</td><td>FB Friend Info</td>
  </tr>
  <td>All Google+ contacts</td><td>GP Info</td>  
  <tr>
  <td>Google+ circle</td><td>GP Group Info</td>  
  </tr>
  <td>Google+ contact</td><td>GP Info</td><td>GP Contact Info</td>  
  <tr>
 </tr>
  </table>
</div>

<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/items/index.android.erb
<h2>Items owned by <b><%= link_to "My Account", account_path %></b></h2>


<table>
	
<% if @items.any? %>
	<tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>
 
<% @items.each do |item| %>
  <tr>
     <td><%= link_to item.description , edit_store_item_path(@store,item) %></td>

  </tr>
<% end %>
<% end %>
<tr>
<td>
<form accept-charset="UTF-8" action="items/new.android" method="get" style="margin:0;padding:0;display:inline">
			<button  type="submit" value="newitem" style="float:left;"  >Add Your Item</button>
</form></td>
</tr>

</table>

app/views/items/index.html.erb
<h2>My rentals</h2>

<table>
	
<% if @items.any? %>
	<tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>
 
<% @items.each do |item| %>
  <tr>
	<% if item.active? %>
     <td><%= link_to item.title , edit_store_item_path(@store,item) %></td>
	<% else %>
	      <td>  <del>  <%= link_to item.title , edit_store_item_path(@store,item) %>  <del>  </td>
	<% end %>

	<% if item.active? %>
	  </del>
	<% end %>  
  </tr>
<% end %>
<% end %>
<tr>
<td>
<form accept-charset="UTF-8" action="items/new" method="get" style="margin:0;padding:0;display:inline">
			<button  type="submit" value="newitem" style="float:left;"  >Add Rental</button>
</form></td>
</tr>

</table>

app/views/items/new.android.erb
<h2>Add an item owned by <b><%= link_to "My Account", account_path %></b></h2>
<%= form_for @item, :url => store_items_path(@store) do |f| %>
<% if @item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :description %><br />
  <%= f.text_field :description %>
</div>
<div class="field">
  <%= f.label :location %><br />
  <%= f.text_field :location %>
</div>
<p/><p/>
<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/items/new.html.erb
<h2>Add Rental</h2>
<%= form_for @item, :url => store_items_path(@store) do |f| %>
<% if @item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<div class="field">
  <%= f.label :location %><br />
  <%= f.text_field :location %>
</div>
<div class="field">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :description %><br />
  <%= f.text_area :description, :cols => 132, :rows => 20  %>
</div>

<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/items/show.android.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @item.description %>
</p>

<p>
  <b>Location:</b>
  <%= @item.location %>
</p>

<p>
  <b>Owner:</b>
  <%= @item.store.name %>
</p>


<%= link_to 'Edit', edit_store_item_path(@store,@item) %> |
<%= link_to 'Items', store_items_path(@store) %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @item.description %>
</p>

<p>
  <b>Location:</b>
  <%= @item.location %>
</p>

<p>
  <b>Owner:</b>
  <%= @item.store.name %>
</p>


<%= link_to 'Edit', edit_store_item_path(@store,@item) %> |
<%= link_to 'Items', store_items_path(@store) %>